-- =============================================================
-- CONTRACT GUARDIAN AI - Seed Data
-- CO1: DML INSERT examples with realistic data
-- =============================================================

-- =============================================================
-- TAGS
-- =============================================================
INSERT INTO tags (name, color) VALUES
    ('High Risk',     '#ef4444'),
    ('Employment',    '#3b82f6'),
    ('NDA',           '#8b5cf6'),
    ('SaaS',          '#06b6d4'),
    ('Investment',    '#f59e0b'),
    ('Supply Chain',  '#10b981'),
    ('Vendor',        '#f97316'),
    ('Partnership',   '#84cc16'),
    ('IP Transfer',   '#ec4899'),
    ('Government',    '#6366f1')
ON CONFLICT (name) DO NOTHING;

-- =============================================================
-- DEMO ADMIN USER (password: Admin@12345 - pbkdf2_sha256 hashed)
-- In production, use proper hashed passwords
-- =============================================================
-- NOTE: This is a placeholder; actual hash generated by the application
INSERT INTO users (id, email, password_hash, full_name, role)
VALUES (
    '00000000-0000-0000-0000-000000000001',
    'admin@contractguardian.ai',
    '$pbkdf2-sha256$29000$placeholder-admin-hash',
    'System Administrator',
    'ADMIN'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO users (id, email, password_hash, full_name, role)
VALUES (
    '00000000-0000-0000-0000-000000000002',
    'analyst@contractguardian.ai',
    '$pbkdf2-sha256$29000$placeholder-analyst-hash',
    'Legal Analyst',
    'ANALYST'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO users (id, email, password_hash, full_name, role)
VALUES (
    '00000000-0000-0000-0000-000000000003',
    'user@contractguardian.ai',
    '$pbkdf2-sha256$29000$placeholder-user-hash',
    'John Doe',
    'USER'
) ON CONFLICT (id) DO NOTHING;
