-- =============================================================
-- CONTRACT GUARDIAN AI - MySQL Seed Data (DML)
-- Converted from PostgreSQL to MySQL 8.0+
-- Step 5: Run AFTER 01_schema_mysql.sql
-- =============================================================

USE contract_guardian;

-- =============================================================
-- TAGS
-- =============================================================
INSERT IGNORE INTO tags (id, name, color) VALUES
    (UUID(), 'High Risk',     '#ef4444'),
    (UUID(), 'Employment',    '#3b82f6'),
    (UUID(), 'NDA',           '#8b5cf6'),
    (UUID(), 'SaaS',          '#06b6d4'),
    (UUID(), 'Investment',    '#f59e0b'),
    (UUID(), 'Supply Chain',  '#10b981'),
    (UUID(), 'Vendor',        '#f97316'),
    (UUID(), 'Partnership',   '#84cc16'),
    (UUID(), 'IP Transfer',   '#ec4899'),
    (UUID(), 'Government',    '#6366f1');

-- =============================================================
-- DEMO USERS
-- NOTE: Passwords below are placeholders.
--       Real hashes are generated by the application.
-- =============================================================
INSERT IGNORE INTO users (id, email, password_hash, full_name, role)
VALUES (
    '00000000-0000-0000-0000-000000000001',
    'admin@contractguardian.ai',
    '-sha256-admin-hash',
    'System Administrator',
    'ADMIN'
);

INSERT IGNORE INTO users (id, email, password_hash, full_name, role)
VALUES (
    '00000000-0000-0000-0000-000000000002',
    'analyst@contractguardian.ai',
    '-sha256-analyst-hash',
    'Legal Analyst',
    'ANALYST'
);

INSERT IGNORE INTO users (id, email, password_hash, full_name, role)
VALUES (
    '00000000-0000-0000-0000-000000000003',
    'user@contractguardian.ai',
    '-sha256-user-hash',
    'John Doe',
    'USER'
);
